// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (name, machine_type, assigned_engineer_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, machine_type, assigned_engineer_id, created_by, created_at
`

type CreateMachineParams struct {
	Name               string      `json:"name"`
	MachineType        string      `json:"machine_type"`
	AssignedEngineerID pgtype.UUID `json:"assigned_engineer_id"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, createMachine,
		arg.Name,
		arg.MachineType,
		arg.AssignedEngineerID,
		arg.CreatedBy,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MachineType,
		&i.AssignedEngineerID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE id = $1
`

func (q *Queries) DeleteMachine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMachine, id)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT id, name, machine_type, assigned_engineer_id, created_by, created_at FROM machines WHERE id = $1
`

func (q *Queries) GetMachine(ctx context.Context, id pgtype.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MachineType,
		&i.AssignedEngineerID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, name, machine_type, assigned_engineer_id, created_by, created_at FROM machines ORDER BY created_at DESC
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MachineType,
			&i.AssignedEngineerID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
