// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (name, machine_type, assigned_engineer_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, machine_type, assigned_engineer_id, created_by, created_at
`

type CreateMachineParams struct {
	Name               string      `json:"name"`
	MachineType        string      `json:"machine_type"`
	AssignedEngineerID pgtype.UUID `json:"assigned_engineer_id"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, createMachine,
		arg.Name,
		arg.MachineType,
		arg.AssignedEngineerID,
		arg.CreatedBy,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MachineType,
		&i.AssignedEngineerID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE id = $1
`

func (q *Queries) DeleteMachine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMachine, id)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT id, name, machine_type, assigned_engineer_id, created_by, created_at FROM machines WHERE id = $1
`

func (q *Queries) GetMachine(ctx context.Context, id pgtype.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MachineType,
		&i.AssignedEngineerID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT
    m.id, m.name, m.machine_type, m.assigned_engineer_id, m.created_by, m.created_at,
    COUNT(ts.id) AS test_site_count
FROM machines m
LEFT JOIN test_sites ts ON ts.machine_id = m.id
GROUP BY m.id
ORDER BY m.created_at DESC
`

type ListMachinesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	MachineType        string             `json:"machine_type"`
	AssignedEngineerID pgtype.UUID        `json:"assigned_engineer_id"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TestSiteCount      int64              `json:"test_site_count"`
}

func (q *Queries) ListMachines(ctx context.Context) ([]ListMachinesRow, error) {
	rows, err := q.db.Query(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesRow
	for rows.Next() {
		var i ListMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MachineType,
			&i.AssignedEngineerID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TestSiteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMachineEngineer = `-- name: UpdateMachineEngineer :one
UPDATE machines SET assigned_engineer_id = $2
WHERE id = $1
RETURNING id, name, machine_type, assigned_engineer_id, created_by, created_at
`

type UpdateMachineEngineerParams struct {
	ID                 pgtype.UUID `json:"id"`
	AssignedEngineerID pgtype.UUID `json:"assigned_engineer_id"`
}

func (q *Queries) UpdateMachineEngineer(ctx context.Context, arg UpdateMachineEngineerParams) (Machine, error) {
	row := q.db.QueryRow(ctx, updateMachineEngineer, arg.ID, arg.AssignedEngineerID)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MachineType,
		&i.AssignedEngineerID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
