// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: points.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoint = `-- name: CreatePoint :one
INSERT INTO points (test_site_id, point_name)
VALUES ($1, $2)
RETURNING id, test_site_id, point_name, created_at
`

type CreatePointParams struct {
	TestSiteID pgtype.UUID `json:"test_site_id"`
	PointName  string      `json:"point_name"`
}

func (q *Queries) CreatePoint(ctx context.Context, arg CreatePointParams) (Point, error) {
	row := q.db.QueryRow(ctx, createPoint, arg.TestSiteID, arg.PointName)
	var i Point
	err := row.Scan(
		&i.ID,
		&i.TestSiteID,
		&i.PointName,
		&i.CreatedAt,
	)
	return i, err
}

const listPointsByTestSite = `-- name: ListPointsByTestSite :many
SELECT id, test_site_id, point_name, created_at FROM points WHERE test_site_id = $1 ORDER BY point_name
`

func (q *Queries) ListPointsByTestSite(ctx context.Context, testSiteID pgtype.UUID) ([]Point, error) {
	rows, err := q.db.Query(ctx, listPointsByTestSite, testSiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Point
	for rows.Next() {
		var i Point
		if err := rows.Scan(
			&i.ID,
			&i.TestSiteID,
			&i.PointName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
