// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_sites.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTestSite = `-- name: CreateTestSite :one
INSERT INTO test_sites (
    machine_id, test_site_number, division, curve_type, curve_number,
    degree_of_curve, section, station, line, km_from, km_to, annual_gmt,
    establishment_date, next_grinding_due_date, next_repainting_due_date, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
RETURNING id, machine_id, test_site_number, division, curve_type, curve_number, degree_of_curve, section, station, line, km_from, km_to, annual_gmt, establishment_date, next_grinding_due_date, next_repainting_due_date, created_at, created_by
`

type CreateTestSiteParams struct {
	MachineID             pgtype.UUID    `json:"machine_id"`
	TestSiteNumber        string         `json:"test_site_number"`
	Division              pgtype.Text    `json:"division"`
	CurveType             pgtype.Text    `json:"curve_type"`
	CurveNumber           pgtype.Text    `json:"curve_number"`
	DegreeOfCurve         pgtype.Text    `json:"degree_of_curve"`
	Section               pgtype.Text    `json:"section"`
	Station               pgtype.Text    `json:"station"`
	Line                  pgtype.Text    `json:"line"`
	KmFrom                pgtype.Numeric `json:"km_from"`
	KmTo                  pgtype.Numeric `json:"km_to"`
	AnnualGmt             pgtype.Numeric `json:"annual_gmt"`
	EstablishmentDate     pgtype.Date    `json:"establishment_date"`
	NextGrindingDueDate   pgtype.Date    `json:"next_grinding_due_date"`
	NextRepaintingDueDate pgtype.Date    `json:"next_repainting_due_date"`
	CreatedBy             pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateTestSite(ctx context.Context, arg CreateTestSiteParams) (TestSite, error) {
	row := q.db.QueryRow(ctx, createTestSite,
		arg.MachineID,
		arg.TestSiteNumber,
		arg.Division,
		arg.CurveType,
		arg.CurveNumber,
		arg.DegreeOfCurve,
		arg.Section,
		arg.Station,
		arg.Line,
		arg.KmFrom,
		arg.KmTo,
		arg.AnnualGmt,
		arg.EstablishmentDate,
		arg.NextGrindingDueDate,
		arg.NextRepaintingDueDate,
		arg.CreatedBy,
	)
	var i TestSite
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.TestSiteNumber,
		&i.Division,
		&i.CurveType,
		&i.CurveNumber,
		&i.DegreeOfCurve,
		&i.Section,
		&i.Station,
		&i.Line,
		&i.KmFrom,
		&i.KmTo,
		&i.AnnualGmt,
		&i.EstablishmentDate,
		&i.NextGrindingDueDate,
		&i.NextRepaintingDueDate,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getTestSite = `-- name: GetTestSite :one
SELECT id, machine_id, test_site_number, division, curve_type, curve_number, degree_of_curve, section, station, line, km_from, km_to, annual_gmt, establishment_date, next_grinding_due_date, next_repainting_due_date, created_at, created_by FROM test_sites WHERE id = $1
`

func (q *Queries) GetTestSite(ctx context.Context, id pgtype.UUID) (TestSite, error) {
	row := q.db.QueryRow(ctx, getTestSite, id)
	var i TestSite
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.TestSiteNumber,
		&i.Division,
		&i.CurveType,
		&i.CurveNumber,
		&i.DegreeOfCurve,
		&i.Section,
		&i.Station,
		&i.Line,
		&i.KmFrom,
		&i.KmTo,
		&i.AnnualGmt,
		&i.EstablishmentDate,
		&i.NextGrindingDueDate,
		&i.NextRepaintingDueDate,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listTestSitesByMachine = `-- name: ListTestSitesByMachine :many
SELECT id, machine_id, test_site_number, division, curve_type, curve_number, degree_of_curve, section, station, line, km_from, km_to, annual_gmt, establishment_date, next_grinding_due_date, next_repainting_due_date, created_at, created_by FROM test_sites WHERE machine_id = $1 ORDER BY test_site_number
`

func (q *Queries) ListTestSitesByMachine(ctx context.Context, machineID pgtype.UUID) ([]TestSite, error) {
	rows, err := q.db.Query(ctx, listTestSitesByMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestSite
	for rows.Next() {
		var i TestSite
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.TestSiteNumber,
			&i.Division,
			&i.CurveType,
			&i.CurveNumber,
			&i.DegreeOfCurve,
			&i.Section,
			&i.Station,
			&i.Line,
			&i.KmFrom,
			&i.KmTo,
			&i.AnnualGmt,
			&i.EstablishmentDate,
			&i.NextGrindingDueDate,
			&i.NextRepaintingDueDate,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
